spring:
  profiles:
    active: dev
    include: secret

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: dudghksdyd12@gmail.com
    password: NEED_TO_INPUT_ON_SECRET
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2

  auth:
    code:
      expiration-minutes: 5  # 5분

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    com.market.allForOneReview: DEBUG
    org.springframework.mail: DEBUG